name: adpro
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - appnope=0.1.4
  - asttokens=3.0.0
  - attrs=25.4.0
  - blas=2.305
  - blas-devel=3.11.0
  - blosc=1.21.6
  - bottleneck=1.4.2
  - branca=0.8.2
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - cffi=1.17.1
  - charset-normalizer=3.4.4
  - click=8.3.1
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - comm=0.2.1
  - contourpy=1.3.3
  - cycler=0.12.1
  - debugpy=1.8.11
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.7.1
  - fiona=1.10.1
  - folium=0.20.0
  - fonttools=4.61.1
  - freetype=2.12.1
  - freexl=2.0.0
  - geopandas=1.1.2
  - geopandas-base=1.1.2
  - geos=3.10.6
  - geotiff=1.7.0
  - giflib=5.2.2
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.11
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.3
  - jpeg=9e
  - json-c=0.16
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kiwisolver=1.4.9
  - lcms2=2.16
  - lerc=4.0.0
  - libarchive=3.7.7
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcurl=8.14.1
  - libcxx=19.1.7
  - libdeflate=1.22
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgdal-core=3.11.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libiconv=1.18
  - libkml=1.3.0
  - liblapack=3.11.0
  - liblapacke=3.11.0
  - libnghttp2=1.57.0
  - libopenblas=0.3.30
  - libpng=1.6.39
  - libsodium=1.0.18
  - libspatialindex=2.1.0
  - libspatialite=5.1.0
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.6.0
  - libxml2=2.13.8
  - libzlib=1.2.13
  - llvm-openmp=19.1.7
  - lz4-c=1.9.4
  - mapclassify=2.10.0
  - markupsafe=3.0.3
  - matplotlib-base=3.10.1
  - matplotlib-inline=0.1.6
  - minizip=4.0.3
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.6.1
  - numexpr=2.11.0
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openblas=0.3.30
  - openjpeg=2.5.2
  - openssl=3.6.1
  - packaging=25.0
  - pandas=2.3.1
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pip=26.0.1
  - platformdirs=4.3.7
  - proj=9.3.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.22
  - pygments=2.19.1
  - pyogrio=0.11.0
  - pyparsing=3.3.2
  - pyproj=3.6.1
  - pysocks=1.7.1
  - python=3.12.3
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.3
  - python_abi=3.12
  - pytz=2025.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - readline=8.3
  - requests=2.32.5
  - rtree=1.4.1
  - scikit-learn=1.8.0
  - scipy=1.17.0
  - setuptools=78.1.1
  - shapely=2.1.1
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.2.0
  - threadpoolctl=3.6.0
  - tk=8.6.15
  - tornado=6.5.1
  - traitlets=5.14.3
  - tzdata=2025c
  - unicodedata2=17.0.1
  - uriparser=0.9.8
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xerces-c=3.2.5
  - xyzservices=2025.11.0
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - astroid==4.0.4
      - dill==0.4.1
      - flake8==7.3.0
      - iniconfig==2.3.0
      - isort==7.0.0
      - librt==0.8.1
      - matplotlib==3.10.8
      - mccabe==0.7.0
      - mypy==1.19.1
      - mypy-extensions==1.1.0
      - pathspec==1.0.4
      - pep8==1.7.1
      - pillow==12.1.1
      - pluggy==1.6.0
      - pycodestyle==2.14.0
      - pyflakes==3.4.0
      - pylint==4.0.4
      - pytest==9.0.2
      - tomlkit==0.14.0
      - typing-extensions==4.15.0
